### ISSUE TITLE
Tag search is not working properly

### ISSUE THREAD

**Issue by NidhiParmar09** [hotwax/threshold-management#143]
Tag search results do not show the "men's" tag when searching for it. However, the "men's" tag appears in the search results when searching for "man."

![Screenshot 2022-11-29 at 11 45 21 AM](https://user-images.githubusercontent.com/113917825/204453165-51ce84ee-883a-4e24-84f5-27c080eb0365.png)
![Screenshot 2022-11-29 at 11 46 10 AM](https://user-images.githubusercontent.com/113917825/204453283-8957d952-c914-4136-a270-3f0c2ae51566.png)

**Comment by adityasharma7** [comment]
Closing as backend issue. Related ticket https://app.clickup.com/t/85zrnnnym
