### ISSUE TITLE
Not displaying error when login with invalid credentials

### ISSUE THREAD

**Issue by Pragyad07** [hotwax/threshold-management#149]
## Current behavior
 When login in with invalid login details the message appears not as expected. It is showing an as:
![Screenshot 2022-12-13 at 10 58 05 AM](https://user-images.githubusercontent.com/64180958/207235130-2eff1c39-65c0-4668-9a5f-f52bfeea1e74.png)

 ## Expected behavior
 When login in with invalid login credentials, a message appears with 'view', which shows the reason for the error.
 https://github.com/hotwax/threshold-management/pull/130
 

 ## Steps to reproduce the issue
 

 ## Can you handle fixing this bug by yourself?

 - [ ] YES
 - [x] NO

 ## Environment details
 
 - Browser: 
 - OS: 
 - Code Version: 

 ## Additional information

**Comment by Pragyad07** [comment]
@shashwatbangar

**Comment by shashwatbangar** [comment]
Only Authorised users will get to see server errors thus **VIEW** button will only be visible to them.

**Comment by Pragyad07** [comment]
Thanks for the info.
