### ISSUE TITLE
Feature to change product store from side menu

### ISSUE THREAD

**Issue by disha1202** [hotwax/threshold-management#151]
## What is the motivation for adding/enhancing this feature?

Currently we can only change the product store from settings page. we need an option to change the product store from side menu footer.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [X] YES
- [ ] NO

**Comment by dt2patel** [comment]
closing issue, not priority right now. will implement as reusable component later.
