### ISSUE TITLE
Changing run time in bulk not working on the save threshold page.

### ISSUE THREAD

**Issue by appurvajain** [hotwax/threshold-management#177]
## Current behavior
When tried to change the runtime in bulk from the save threshold page, it was successful the first time. When tried again, the clock was disabled.

 ## Expected behavior
Clicking on the runtime, a calendar clock should appear to enable changing runtime in bulk.

 ## Steps to reproduce the issue
 

 ## Can you handle fixing this bug by yourself?

 - [ ] YES
 - [ ] NO

 ## Environment details
 
 - Browser: 
 - OS: 
 - Code Version: 

 ## Additional information

**Comment by ymaheshwari1** [comment]
The date-time selector does not opens up on second time as the component does not gets unmounted after a successfull schedule.
