### ISSUE TITLE
Add close button to tag modal

### ISSUE THREAD

**Issue by dt2patel** [hotwax/threshold-management#193]
## What is the motivation for adding/enhancing this feature?

The "add tag" modal doesn't have a dedicated button for closing it which makes it confusing for the user when they are don't selecting their tags and want to exit the screen. Adding screenshot for proposed UI of closing modal.

<img width="954" alt="Screenshot 2023-02-23 at 4 23 28 PM" src="https://user-images.githubusercontent.com/60128132/220886785-2cd966fd-fd03-464e-95c3-64655acc0dfd.png">

**Comment by k2maan** [comment]
@dt2patel sir, a close button is there in the 'include tags' modal already, do we need to make any other changes?

![threshold](https://user-images.githubusercontent.com/59442907/229774395-bd26e853-641b-44ea-8545-6698a2ce837c.png)

**Comment by dt2patel** [comment]
@k2maan a close button doesn't communicate to the user that their changes will be saved
