### ISSUE TITLE
Hide item-divider when channels are not found

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/threshold-management#228]
## Current behavior
 
The item divider for channels is always displayed on UI even when channels are not present in facility resulting in confusion.

 ## Expected behavior
 
If the channels are not present on facility the item-divider should not be displayed.

Handle the below case as well:
https://github.com/hotwax/threshold-management/issues/228#issuecomment-1878176719

 ## Steps to reproduce the issue
 
- Login to a instance on which facility channels are not present
- Go to Create Rule page
- Enter threshold and then click on save threshold button
- Verify that the channels divider is always displayed even when facility channels are not available.

 ## Can you handle fixing this bug by yourself?

 - [x] YES
 - [ ] NO

 ## Environment details
 
 - Browser: 
 - OS: 
 - Code Version: 

 ## Additional information
 
![image](https://github.com/hotwax/threshold-management/assets/41404838/02ac7c79-f23b-4f5c-beec-c5e1b4e35315)

**Comment by ymaheshwari1** [comment]
Also I think we can move the channel options at the last of the list after `name` and `run time`options.

Wdyt @dt2patel ?

**Comment by dt2patel** [comment]
agreed @ymaheshwari1

**Comment by ymaheshwari1** [comment]
> agreed @ymaheshwari1

Ok, adding it into this issue's scope.

**Comment by ymaheshwari1** [comment]
Also move the channel options at the last of the list after `name` and `runtime` option.
