### ISSUE TITLE
Add functionality to the facilities segment of Store Pickup and Shipping Rules page.

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/threshold-management#264]
## What is the motivation for adding/enhancing this feature?

Currently we only have ui for the facilities segment of Store pickup and Shipping Rules page. Add the functionality to it and make it working.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by amansinghbais** [comment]
Here a discussion is needed over the functionality of facility segment in store pickup page, So for now only the implementation of the facility segment in Shiping page is done in following PR: https://github.com/hotwax/threshold-management/pull/265

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v3.0.0. Hence, closing it.
