### ISSUE TITLE
Display unique product features

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/threshold-management#271]
## Current behavior
 
When selecting product features for defining threshold, duplicate features gets displayed.

 ## Expected behavior
 
Only unique features should be displayed.

 ## Steps to reproduce the issue
 

 ## Can you handle fixing this bug by yourself?

 - [x] YES
 - [ ] NO

 ## Environment details
 
 - Browser: 
 - OS: 
 - Code Version: 

 ## Additional information
 
![image](https://github.com/hotwax/threshold-management/assets/41404838/0afd8163-3ee5-4545-961a-202d5b6e5aee)

**Comment by Adameddy26** [comment]
Verified and working fine in release v3.0.0. Hence, closing it.
