### ISSUE TITLE
Show product information on the product select page.

### ISSUE THREAD

**Issue by dt2patel** [hotwax/threshold-management#28]
On the product select page:

User should be able to search products like our other apps.
Results should be grouped by parent product
Products should be selectable

**Comment by dt2patel** [comment]
products do not need to be selectable, if everything else is handled, we can close.

**Comment by ymaheshwari1** [comment]
Product search and grouping of products on the basis of parent product is working as expected.

![image](https://user-images.githubusercontent.com/41404838/217433102-7de41f89-2a8f-45f7-838c-64bf8e1bf4d8.png)

**Comment by ymaheshwari1** [comment]
Closing as done
