### ISSUE TITLE
ATP App Phase I Testing

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/threshold-management#287]
## Issues List 
1. Settings page -> Product store selection -> In case of blank username, IDs should be visible. Same case should be handled for menu footer.
2. Safety Stock - >Threshold rule empty state is present instead of safety stock. Also empty state not present for shipping and inventory channels.
3. Threshold, safety stock -> Decimal points are getting saved.
4. Browser timezone, Selected timezone -> Missing. Also cross icon is not visible in the modal.
5. Store Pickup - Scheduler is present even when no rules are created.
6. User is able to set the group name empty on edit. Also group can be created with blank name(space given).

**Comment by Adameddy26** [comment]
Verified the fixes in dev environment of App and found that empty state messages doesn't seem uniform. Therefore , reopening it. Rest all fixes are working fine.

https://jam.dev/c/99b71f72-9e58-43f7-8dfb-29062de11362

**Comment by Adameddy26** [comment]
Verified the fixes in DEV environment of App wherein found that
1. Selected timezone is not persisting when user login again after the logout. Also the selected option of timezone is not appearing checked.
2. No empty state is present when all existing rules are archived. (all 4 sections)

Therefore, reopening this ticket.

**Comment by amansinghbais** [comment]
For the first point, As discussed earlier we don't have support for timezone selector in our app. Hence the timezone selector is not working as of now.

For the second point i have fixed it and created a PR.

**Comment by Adameddy26** [comment]
All the issues mentioned in this ticket are working fine. Hence, closing this ticket.
