### ISSUE TITLE
Fetch inventory channels only for the current selected product store

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/threshold-management#302]
## What is the motivation for adding/enhancing this feature?

Currently we are fetching all the inventory channels irrespective of selected product store. We should show only groups which are associated with the current product store.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v3.0.0.
