### ISSUE TITLE
Fix inventory channels page segment not coming in line with the title

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/threshold-management#305]
## Current behavior
 
Currently the segment selector in inventory channels page comes below page title.
![Screenshot from 2024-05-10 10-30-28](https://github.com/hotwax/threshold-management/assets/69574321/98f29fa2-17a0-4e3e-85db-1d6ac6d13cff)

 ## Expected behavior
 
The segment should comes in same line with the page title.

 ## Steps to reproduce the issue
 

 ## Can you handle fixing this bug by yourself?

 - [ ] YES
 - [ ] NO

 ## Environment details
 
 - Browser: 
 - OS: 
 - Code Version: 

 ## Additional information

**Comment by Adameddy26** [comment]
Verified and working fine in release v3.0.0.
