### ISSUE TITLE
ATP App Testing Phase III

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/threshold-management#313]
## Issues List 
 1. Create a rule in Threshold/Safety Stock/Store Pickup/Shipping -> Select product tags/features ->Go back and open the create rule page -> Old selection persists on UI.
 2. Create a rule in Product&Channels tab for Store Pickup/Shipping -> Open create rule page in Product&Facilities tab -> Go back -> User is navigated to Product&Channels tab instead of Product&Facilities.
 3. Store Pickup -> Product&Channels -> Create new rule -> Not visible in list just after creation.
 4. No empty state present for scheduler history.
 5. Multiple 'Click backdrop to dismiss' messages are prompted on UI and continous loading occurs when user creates a rule or channel group and changes the product store.
 6. Store Pickup -> Create a rule (select facilities) -> Selected facilities are not visible in card after rule creation.
 7. If an inventory channel group is created using existing group name then in this case config facilities selected for previously created channel groups are getting changed to new group selected config facility. Also selected facilities and warehouses of previously created channel groups are getting set for the newly created channel group.
 8. If inventory channel group name is removed and saved on edit then in 'Include facilities group' modal, checkboxes are visible with empty group name.
 9. Selection of facilities in create rule page when the page is opened from product&channels tab. Same for channels when user tries to create a rule from product&facilities tab. Both of these should not be allowed.
 10. 'No channel found for current product store'. This empty message is visible on clicking create rule button for the product store for which no channels are configured. First of all 'current' can be changed to 'selected'. Also in this case user is unable to create any rule as channel selection is mandatory. User should be notified with a proper message keeping save button as disabled.
 11. User is able to update and save the same value which is previously set in case of threshold and safety stock.
 12. If window width is reduced then in this case, section heading is not visible.
 13. In the product features selection modal, when the user scrolls to the bottom of the list, the loader becomes visible briefly, and the scroll position resets to the top.

**Comment by amansinghbais** [comment]
Here in 8th point, while we try creating group using existing facility group id the api should give give error, but in our case it is not giving any error instead updating the group. This should be handled from the backend.

**Comment by Adameddy26** [comment]
There are few more issues I have found while testing the fixes of above mentioned issues.

1. Open product store dropdown and then reduce the frame size manually or by opening the devtools.(related with point 12)
2. Shipping -> Edit group -> Toggle ON /OFF not working.
3. Shipping rule can be created without name or selecting any facility/channel.
4. Threshold/Safety stock/Store pickup/Shipping -> Edit any created rule -> Save without any change -> Selected facilities and channels are getting unchecked.
5. Shipping -> Facility -> Choose No capacity option -> Now choose custom option -> 0 is visible instead of blank value -> Try to save -> Take note of toast message -> Now rewrite the 0 in the same field and try to save -> Take note of toast message.
6. Try to save the rule without selecting any facility group or channel -> Toast 'Please select atleast one config facility/facility group' -> This toast should be changed to 'Please select atleast one channel/facility'.
7. Threshold/Safety stock  -> Create rule -> input field of safety stock and threshold is inserting the negative value on clicking the down arrow. Also in case of safety stock the rule is getting saved with the negative value.
8. Safety stock -> Create rule -> Select newly created tag/feature -> Provide name and safety stock value -> Select facility -> Save the rule -> Observe the issue -> Tags and features added are getting disappeared.

@amansinghbais Please look into the same.

**Comment by Adameddy26** [comment]
Found 2 issues after the fixes/new changes - 
1. Create first rule in threshold/safety stock/shipping/store pickup for any product store -> Once the scheduler gets visible, run now the scheduler without setting the schedule for a particular time frequency -> Open the scheduler history -> Observe the issue.
2. Shipping -> Facility -> User is not able to set the max order fulfillment capacity for a facility.

Considering the above two issues; reopening this ticket.
@amansinghbais Please look into the same.

**Comment by amansinghbais** [comment]
Fixed the above issues in following PR: https://github.com/hotwax/threshold-management/pull/338

**Comment by Adameddy26** [comment]
Verified all issues and are working fine in release v3.0.0. Hence, closing it.
