### ISSUE TITLE
Inconsistent Selection of Facilities Between Included and Excluded Sections

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/threshold-management#320]
## Current behavior
 Facilities intermittently appear selected in both the included and excluded sections, leading to confusion and incorrect rule configurations.
 
 ## Expected behavior
 Facilities selected for inclusion should only be reflected in the inclusion section, and similarly, facilities selected for exclusion should solely appear in the exclusion section. There should be no crossover between the two sections.

 ## Steps to reproduce the issue
Navigate to the rule creation interface of safety stock/store pickup/shipping.
Select facilities for inclusion and exclusion.
Observe that facilities intended for inclusion might appear selected in the exclusion section and vice versa.
Attempt to replicate the issue under various conditions.

 ## Environment details
 App version : THRESHOLD-2.0-CD334B8
 App environment : DEV

 ## Additional information
https://jam.dev/c/fc44f7e2-9453-4cc0-aaa6-d2b2f61af274
Refer last 40 sec of this video to observe the issue.

**Comment by amansinghbais** [comment]
Here in this issue, the click event is applied globally over the ion-item instead of ion-checkbox which results in click event to be triggered in case where checkbox is not present for items already applied in another type.

Hence added a check to allow click event for actionable items only.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v3.0.0. Hence, closing it.
