### ISSUE TITLE
Fix channels not showing up in rule card on productAndChannel segment

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/threshold-management#323]
## Current behavior
 
Currently the ruleCard data is not updating based on selected segment.

 ## Expected behavior
 
The rule card should update based on the selected segment.

 ## Steps to reproduce the issue
 

 ## Can you handle fixing this bug by yourself?

 - [ ] YES
 - [ ] NO

 ## Environment details
 
 - Browser: 
 - OS: 
 - Code Version: 

 ## Additional information

**Comment by Adameddy26** [comment]
Verified and working fine in release v3.0.0.
