### ISSUE TITLE
Issue with Facility and Channel Selection Unchecked After Saving Unchanged Rule Edit

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/threshold-management#331]
## Expected behavior
The selected facilities and channels should remain checked even after saving the rule without changes.

## Steps to reproduce the issue
Navigate to the rule related to "Threshold/Safety stock/Store pickup/Shipping".
Open edit rule page of any rule.
Save the rule without making any changes.
Reopen the edit rule page.
Observe the issue.

 ## Environment details
 App version : THRESHOLD-2.0-2C00FE9
 App environment : DEV

 ## Additional information
 https://jam.dev/c/00f26208-bd93-440f-97a6-7f6136c4536d

**Comment by amansinghbais** [comment]
Fixed this issue in following PR: https://github.com/hotwax/threshold-management/pull/336

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v3.0.0. Hence, closing it.
