### ISSUE TITLE
Add SSO support

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/threshold-management#337]
## What is the motivation for adding/enhancing this feature?

-  Enable SSO in order routing using launchpad, use the ofbiz token to login into launchpad

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v3.0.0. Hence, closing this ticket.
