### ISSUE TITLE
Reset button and List header label should have space between them.

### ISSUE THREAD

**Issue by dt2patel** [hotwax/threshold-management#41]
The list header content on the find product page right now has the button right next to the label. Instead they should be on opposite ends.

<img width="455" alt="Screen Shot 2022-05-05 at 3 30 58 PM" src="https://user-images.githubusercontent.com/60128132/166901787-17eb9725-e225-4eaa-8882-3bf9d58b8723.png">

**Comment by Nihu-Sharma** [comment]
Fixed the button by giving the space between property in the SlelectProduct page for the reset button.
